### ISSUE TITLE
Dual monitor problem

### ISSUE THREAD

**Issue by woutercools** [Lacro59/playnite-descriptioneditor-plugin#19]
When I open the Description Editor on my dual monitor setup, it stretches across the full length of my 2 screens.
If I resize it to only 1 screen, the next time it opens again across the 2 screens.
It doesn't remember the last used size and position.

![image](https://github.com/Lacro59/playnite-descriptioneditor-plugin/assets/16439116/20a8ebbd-3bea-4a6e-9d00-3cb0c88f2384)

It didn't do this before, but I guess it got introduced by a plugin update.

Can it be corrected so that the plugin remembers the last used size and position?

Thanks.

**Comment by Kyzoku** [comment]
I'm having this issue as well.
