### ISSUE TITLE
Problems with ultrawide screen and more than one monitor

### ISSUE THREAD

**Issue by Idecman** [Lacro59/playnite-descriptioneditor-plugin#20]
As a user said in [this thread](https://github.com/Lacro59/playnite-descriptioneditor-plugin/issues/19),  the DescriptionEditor window is stretched with more than one monitor, occupying all connected monitors.
Also (this since about a week ago, it didn't happen before), when opening it normally on an ultrawide monitor (21:9), it occupies the full width of the monitor (sometimes also the full height, but without being maximized).

Sometimes like this:
![st](https://github.com/Lacro59/playnite-descriptioneditor-plugin/assets/40704202/dc26a526-5f01-4418-b36a-3dc686273408)

Sometimes like this:

![st02](https://github.com/Lacro59/playnite-descriptioneditor-plugin/assets/40704202/d03d1fb5-9720-456b-9425-5a244dec950a)

Thank you very much for your help.

**Comment by azuravian** [comment]
To add to this, in case it helps, I have a 3 monitor setup, with a standard widescreen (1440p) in the center and 2 portrait 1440x900, 1 on each side.

In my case, the description editor is the size of the full width of all 3 screens, but starts at the middle screen (which is where I'm running Playnite).  The width of the first monitor extends outside of the active space, so I can't even see the buttons to close without moving the window.

**Comment by Kyzoku** [comment]
Mine also extends outside and I have to move the window to close.

**Comment by Lacro59** [comment]
duplicate #19
